### ISSUE TITLE
500 error when submitting form on production server

### ISSUE THREAD

**Issue by wwwroth** [HubSpot/hubspot-php#124]
This form submit works fine locally but fails on staging and production. Here's the error dump. Any idea?

```
[2017-10-05 18:15:13] live.ERROR: GuzzleHttp\Exception\ServerException: Server error: `POST https://forms.hubspot.com/uploads/form/v2/2980484/49545648-97a8-455e-8eea-f8458de740e7` resulted in a `500 Internal Server Error` response:

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>S (truncated...)
 in /home/giftogramwww/html/dev/site/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/giftogramwww/html/dev/site/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /home/giftogramwww/html/dev/site/vendor/ryanwinchester/hubspot-php/src/Http/Client.php(100): GuzzleHttp\Client->request('post', 'https://forms.h...', Array)
#11 /home/giftogramwww/html/dev/site/vendor/ryanwinchester/hubspot-php/src/Resources/Forms.php(26): SevenShores\Hubspot\Http\Client->request('post', 'https://forms.h...', Array, NULL, false)
#12 /home/giftogramwww/html/dev/site/app/Http/Controllers/HubspotController.php(137): SevenShores\Hubspot\Resources\Forms->submit('2980484', '49545648-97a8-4...', Array)
#13 /home/giftogramwww/html/dev/site/app/Http/Controllers/ContactController.php(44): Frontend\Http\Controllers\HubspotController->submitForm('49545648-97a8-4...', Object(Illuminate\Http\Request))
#14 [internal function]: Frontend\Http\Controllers\ContactController->submitForm(Object(Illuminate\Http\Request), 'sales')
#15 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#16 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('submitForm', Array)
#17 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Frontend\Http\Controllers\ContactController), 'submitForm')
#18 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#19 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(305): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(209): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(237): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#49 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#50 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#51 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /home/giftogramwww/html/dev/site/public/index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main}

Next SevenShores\Hubspot\Exceptions\BadRequest: HTTP/1.1 500 Internal Server Error
Date: Thu, 05 Oct 2017 18:15:02 GMT
Server: Apache
X-Powered-By: PHP/7.0.21
Content-Length: 3301
Connection: close
Content-Type: text/html; charset=UTF-8


<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: ThisDomain</p>
<p>Filename: config/config.php</p>
<p>Line Number: 553</p>


	<p>Backtrace:</p>






			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/application/config/config.php<br />
			Line: 553<br />
			Function: _error_handler			</p>










			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/index.php<br />
			Line: 315<br />
			Function: require_once			</p>




</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: ThisDomain</p>
<p>Filename: config/config.php</p>
<p>Line Number: 587</p>


	<p>Backtrace:</p>






			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/application/config/config.php<br />
			Line: 587<br />
			Function: _error_handler			</p>










			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/index.php<br />
			Line: 315<br />
			Function: require_once			</p>




</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  mysqli::real_connect(): (HY000/2002): Connection timed out</p>
<p>Filename: mysqli/mysqli_driver.php</p>
<p>Line Number: 202</p>


	<p>Backtrace:</p>
















			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/application/core/MY_Controller.php<br />
			Line: 50<br />
			Function: database			</p>




			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/application/controllers/Vanity.php<br />
			Line: 21<br />
			Function: __construct			</p>






			<p style="margin-left:10px">
			File: /home/giftogramredeemwww/html/index.php<br />
			Line: 315<br />
			Function: require_once			</p>




</div><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Database Error</title>
<style type="text/css">

::selection { background-color: #E13300; color: white; }
::-moz-selection { background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Unable to connect to your database server using the provided settings.</p><p>Filename: controllers/Vanity.php</p><p>Line Number: 21</p>	</div>
</body>
</html> in /home/giftogramwww/html/dev/site/vendor/ryanwinchester/hubspot-php/src/Http/Client.php:102
Stack trace:
#0 /home/giftogramwww/html/dev/site/vendor/ryanwinchester/hubspot-php/src/Resources/Forms.php(26): SevenShores\Hubspot\Http\Client->request('post', 'https://forms.h...', Array, NULL, false)
#1 /home/giftogramwww/html/dev/site/app/Http/Controllers/HubspotController.php(137): SevenShores\Hubspot\Resources\Forms->submit('2980484', '49545648-97a8-4...', Array)
#2 /home/giftogramwww/html/dev/site/app/Http/Controllers/ContactController.php(44): Frontend\Http\Controllers\HubspotController->submitForm('49545648-97a8-4...', Object(Illuminate\Http\Request))
#3 [internal function]: Frontend\Http\Controllers\ContactController->submitForm(Object(Illuminate\Http\Request), 'sales')
#4 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#5 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('submitForm', Array)
#6 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Frontend\Http\Controllers\ContactController), 'submitForm')
#7 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#8 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(305): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#12 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(209): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#15 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /home/giftogramwww/html/dev/site/app/Http/Controllers/Controller.php(237): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(120): Frontend\Http\Controllers\Controller->Frontend\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#18 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /home/giftogramwww/html/dev/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#46 /home/giftogramwww/html/dev/site/public/index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#47 {main}
```

**Comment by ksvirkou** [comment]
@wwwroth
I can't reproduce it
more over I see that there was a problem in your mysql connection
in case of you still see this problem let me know
